[Variables]
; ---------- Theme ----------
ThemeCount=6
; Change this as the theme count changes

; Follow the format below and add your own themes!
; The colors here are approzimately the same as the original color in the movie
Theme1=White
Color1=255,255,255

Theme2=Blue
Color2=100,232,237

Theme3=Yellow
Color3=255,213,76

Theme4=Orange
Color4=246,106,53

Theme5=Green
Color5=115,227,71

Theme6=Purple
Color6=214,73,183


; ---------- General ----------
Font=Encom
; encom-webfont is the default font for this suite. It only supports capital letters
; so most of the skins will automatically set the letters to UPPERCASE
;
; Cool Fact: Type 'TRON' with this font and the 'T' and 'R' sticks! 

ScreenHeight=768

CurrentTheme=Blue
; The current theme selected
; (Controlled by the Theme skin)

CurrentColor=100,232,237
; The current theme color
; (Controlled by the Theme skin)

; ---------- Clock ----------
TimeAlpha=185
WeekdayAlpha=255
DMYAlpha=185

; ---------- Honeycomb ----------
Size=70
; The size of the honercombs' width and height
